# Generated by Django 2.2 on 2020-08-25 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping_Record',
            fields=[
                ('mapping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('schema_json', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(blank=True, max_length=36, null=True)),
                ('role_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.CharField(default='timestamprequired', max_length=40)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Select The Gender Choices'), (1, 'Male'), (2, 'Female')], null=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='email address')),
                ('enabled', models.IntegerField()),
                ('last_login', models.CharField(default='timestamprequired', max_length=40)),
                ('phone', models.CharField(help_text='The mobile number to deliver tokens to.', max_length=16, unique=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_on', models.CharField(default='timestamprequired', max_length=40)),
                ('username', models.CharField(default='timestamprequired', max_length=40)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='galilio.Roll')),
            ],
        ),
        migrations.CreateModel(
            name='Upload_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(blank=True, max_length=36, null=True)),
                ('row_count', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_at', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('mapping_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='galilio.Mapping_Record')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_id', models.CharField(blank=True, max_length=36, null=True)),
                ('permission_name', models.CharField(blank=True, max_length=255, null=True)),
                ('permission_type', models.CharField(blank=True, max_length=255, null=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='galilio.Roll')),
            ],
        ),
    ]
